export const SUPABASE_URL = "https://ngtsyzkodhotrrrfxdmq.supabase.co";
export const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ndHN5emtvZGhvdHJycmZ4ZG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxMDM1NzksImV4cCI6MjA5NzY3OTU3OX0.Z58A5aKwZ_2hoS_cH5tlh9wJuzjm1hjm7xpnLtE5qPk";
export const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);